allprojects {
    apply plugin: 'eclipse'
}

subprojects {
    plugins.withType(JavaPlugin) {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
        tasks.withType(JavaCompile) {
            options.encoding = 'UTF-8'
            options.release.set(11)
        }
    }
}
